core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.admin.views.decorators import staff_member_required

app_name = 'core'

admin.site.login = staff_member_required(admin.site.login, login_url='')

urlpatterns = [
    path('admin/', admin.site.urls  ),
    path("", include('pages.urls'), name ='pages'),
]

pages/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import LogoutView, LoginView, SignupView, HomeView, dropdownView
from agendamento.views import AgendamentoView, ListagemView

app_name = 'pages'

urlpatterns = [
    
    # Non-LoginRequired URLs
    path('', HomeView.as_view()         , name='home'),
    path('signup/', SignupView.as_view(), name= 'signup'),
    path('login/', LoginView.as_view()  , name='login'),
    
    #Login Required URLs
    path('logout/'      , login_required(LogoutView.as_view())      , name="logout"),
    path('agendamento/' , login_required(AgendamentoView.as_view()) , name="agendamento"),
    path('listagem/'    , login_required(ListagemView.as_view())    , name="listagem"),
    
    #UTILS
    path('ajax/carregar-horarios/', dropdownView.send_horarios_data, name="ajax_carregar_horarios" ) #Dependent DropDownList

]

agendamento/models.py
from django.db import models
from .validators import previous_date_validator, time_validator, weekday_validator
import datetime as dt

from core import settings

class Estabelecimento(models.Model):
    nome = models.CharField(max_length=255)
    cnes = models.CharField(max_length=75)

    def __str__(self):
        return f"{self.nome} ( {self.cnes} )"

class Agendamento(models.Model):
    id = models.AutoField(primary_key=True)
    estabelecimento = models.ForeignKey(Estabelecimento, on_delete=models.CASCADE)
    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank = True,
    )
    
    appointment_date = models.DateField(validators= [previous_date_validator, weekday_validator])
    appointment_hour = models.TimeField(validators= [time_validator])

    is_active = models.BooleanField(default=True)
    
    @property
    def quantidade_vagas(self):
        appointment = self.objects.get(id = self.id)
        return appointment.users.all().count()
    
    @property
    def is_expired(self):
        if dt.date.today() > self.appointment_date \
        or ( dt.date.today() == self.appointment_date \
             and dt.datetime.now().time() > ( self.appointment_hour )
           ):
            return True
        return False

    @property
    def weekday(self):
        days = ['Segunda', 'Terça-Feira', 'Quarta-Feira', 'Quinta-Feira', 'Sexta-Feira', 'Sábado', 'Domingo']
        return "{:2}".format(days[dt.date.weekday(self.appointment_date)])
    
    @property
    def estabelecimento_formated(self):
        return f"{ self.estabelecimento.cnes} - {self.estabelecimento.nome}"

    def __str__(self):
        return f"{self.weekday} , {self.appointment_date} ({self.appointment_hour})"
    

agendamento/forms/agendamentoForm.py
from logging import PlaceHolder
import re
from urllib import request
from django import forms
from agendamento.models import Estabelecimento, Agendamento
import datetime as dt

class AgendamentoForm(forms.Form):
    estabelecimento_Field = forms.ModelChoiceField(
        label= "Estabelecimentos",
        queryset=Estabelecimento.objects.all(),
        widget= forms.Select(
            attrs={
                'class': 'form-control',
            }
        ),
        empty_label= "Selecione um Estabelecimento"
    )
    
    horario_Field = forms.ModelChoiceField(
        label= "Horários Disponiveis",
        queryset= Agendamento.objects.none(),
        widget= forms.Select(
            attrs={
                'class': 'form-control',
            }
        ),
        empty_label= "Verifique os Horários Disponíveis"
    )

    def agendar(self, request):

        if 'estabelecimento_Field' in self.data:
            estabelecimento_id = int(self.data.get('estabelecimento_Field'))
            self.fields['horario_Field'].queryset = Agendamento.objects.filter(estabelecimento_id = estabelecimento_id)
            

            horario_formatado = re.search(r'\((.*?)\)',self.data.get('horario_Field')).group(1)\
                .split(sep=':')
            
            data_formatada = re.search(r'\,(.*?)\(',self.data.get('horario_Field')).group(1)\
                .strip(' ')\
                .split(sep = '-')
            
            # Partes do Horario_formatado
            hora     = int(horario_formatado[0])
            minutos  = int(horario_formatado[1])
            segundos = int(horario_formatado[2])

            # Partes da data_formatada
            ano = int(data_formatada[0])
            mes = int(data_formatada[1])
            dia = int(data_formatada[2])

            # Agendamento Selecionado
            agendamento = Agendamento.objects\
                .filter(estabelecimento_id = estabelecimento_id) \
                .filter(appointment_hour = dt.time(hora, minutos, segundos))\
                .filter(appointment_date = dt.date(ano, mes, dia))\
                .first() # Queryset -> Agendamento
            
            # Verifica se o Agendamento tem menos de 5 usuários cadastrados (vagas livres)
            # e se o Usuário tem algum agendamento não expirado
            # ou o caso em que o Usuário não tem nenhum agendamento cadastrado
            if  ( agendamento.users.count() < 5 and self.has_no_expired_appointment(request.user) ) \
            or  not agendamento:
                agendamento.users.add(request.user)
            else:
                raise forms.ValidationError("Impossibilitado de realizar agendamento - Você já tem um agendamento não-expirado ou não há vagas para esse agendamento")
        elif self.instance.pk:
            self.fields['horario_Field'].queryset = self.instance.establecimento_Field

    def has_no_expired_appointment(self, user):
        if(Agendamento.objects.filter(users = user).exists()):
            for user_appointment in Agendamento.objects.filter(users = user):
                if(user_appointment.is_expired == False):
                    return False
            return True
        else:
            return True

agendamento/views/agendamentoView.py
from django.forms import ValidationError
from django.views.generic.edit import FormView
from django.utils.translation import gettext_lazy as _

from django.contrib import messages

from agendamento.forms import AgendamentoForm

class AgendamentoView(FormView):
    template_name = 'agendamento/agendamento.html'
    form_class    = AgendamentoForm
    success_url   = '/listagem/'
    
    #Por conta do DropDownList, a validação fica por conta do AgendamentoForm 
    def form_invalid(self, form):
        try:
            form.agendar(self.request)
        except ValueError: # Caso o Usuário nao coloque um estabelecimento o formulario irá subir um Value Error por conta do estabelecimento_id ser ""
                           #, impossibilitando o casting [ int(estabelecimento_id) ]
            messages.add_message(
                self.request,
                messages.ERROR,
                "Estabelecimento Inválido - Por favor, selecione um Estabelecimento válido"
            )
        
        except AttributeError as e: # Caso o Usuário não selecione um Horário
            messages.add_message(
                self.request,
                messages.ERROR,
                "Horário Inválido - Por favor, selecione um horário válido"
            )
        
        except ValidationError as e: # Caso o Usuário já esteja cadastrado ou não haja vagas no agendamento Selecionado
            messages.add_message(
                self.request,
                messages.ERROR,
                e.message
            )
        
        except: # Qualquer outro caso
            messages.add_message(
                self.request,
                messages.ERROR,
                "Ocorreu um erro no agendamento"
            )
            
        return super().form_valid(form) # Em todos os casos ele é enviado à listagem, caso haja erro haverá um botão para voltar para o agendamento
        

agendamento/views/listagemView.py
from django.shortcuts import render
from django.views import View

from agendamento.models import Agendamento

class ListagemView(View):
    model = Agendamento
    template_name = 'agendamento/listagem.html'

    def get(self,request):
        context = {
            'agendamento': Agendamento.objects.filter(users  = request.user)
        }

        return render(request, self.template_name, context)

templates/agendamento/agendamento.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    AutoCadastro
{% endblock title %}
{% block content %}
    <form method="post"
          id="agendamentoForm_id"
          horarios-data="{% url 'pages:ajax_carregar_horarios' %}"
          novalidate>
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label }}
                <br>
                {{ field }}
            </p>
        {% endfor %}
        <button type="submit" class="btn btn-primary btn-block mb-4">Agendar</button>
    </form>
    {% block script %}
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src= "{% static 'js/utils/dropdownJS.js' %}"></script>
    {% endblock %}
{% endblock content %}

templates/agendamento/listagem.html
{% extends 'base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        <div class='row'>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger" role="alert">{{ message }} - <a href="{% url 'pages:agendamento' %}">Clique aqui para realizar o agendamento novamente</a></div>
                {% endfor %}
            {% endif %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Data e Horario de Agendamento</th>
                        <th scope="col">Dia da Semana</th>
                        <th scope="col">Agendamento Passou do Horario?</th>
                        <th scope="col">Estabelecimento</th>
                    </tr>
                </thead>
                <tbody>
                    {% for exame in agendamento %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ exame.appointment_date }} - {{ exame.appointment_hour }}</td>
                            <td>{{ exame.weekday }}</td>
                            {% if exame.is_expired %}
                                <td>Agendamento Expirado</td>
                            {% else %}
                                <td>Dentro do Horário</td>
                            {% endif %}
                            <td>{{ exame.estabelecimento_formated }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p>
            Você não está autenticado
        </p>
    {% endif %}
{% endblock content %}