core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.admin.views.decorators import staff_member_required

app_name = 'core'

admin.site.login = staff_member_required(admin.site.login, login_url='')

urlpatterns = [
    path('admin/', admin.site.urls  ),
    path("", include('pages.urls'), name ='pages'),
]

pages/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import LogoutView, LoginView, SignupView, HomeView, dropdownView
from agendamento.views import AgendamentoView, ListagemView

app_name = 'pages'

urlpatterns = [
    
    # Non-LoginRequired URLs
    path('', HomeView.as_view()         , name='home'),
    path('signup/', SignupView.as_view(), name= 'signup'),
    path('login/', LoginView.as_view()  , name='login'),
    
    #Login Required URLs
    path('logout/'      , login_required(LogoutView.as_view())      , name="logout"),
    path('agendamento/' , login_required(AgendamentoView.as_view()) , name="agendamento"),
    path('listagem/'    , login_required(ListagemView.as_view())    , name="listagem"),
    
    #UTILS
    path('ajax/carregar-horarios/', dropdownView.send_horarios_data, name="ajax_carregar_horarios" ) #Dependent DropDownList

]

pages/views/homeView.py
from django.views import View
from django.shortcuts import render

from users.models import User

class HomeView(View):
    model = User
    template_name = 'home.html'

    def get(self, request):
        return(render(request, self.template_name, context = {'user' : request.user} ))

templates/base.html
<!doctype html>
<html lang="pt-br" class="h-100">
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap -->
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
        <link rel='stylesheet' href="{% static 'style/custom.css' %}">
        <!-- Bloco de Título da Página -->
        <title>
            {% block title %}{% endblock %}
        </title>
        {% block headInner %}
        {% endblock headInner %}
    </head>
    <body class="h-100">
        <nav class="navbar navbar-dark mb-4" style="background-color: #195eb2;">
            <div class="container">
                <a class="navbar-brand" href="{% url "pages:home" %}">
                    <img class="img-fluid logo" src="{% static 'assets/lais_logo.png' %}" />
                </a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'pages:logout' %}">Encerrar Sessão</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <!--Bloco Content-->
        <div  class="mx-5 d-flex justify-content-center row">
        {% block content %}{% endblock %}
        </div>
        <!-- Booststrap -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% block script %}{% endblock %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Página Inicial{% endblock %}
{% block navItems %}{% endblock %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success container" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% if user.is_authenticated %}
        <div class="card" style="width: 20rem;">
            <div class="card-body">
                <h5 class="card-title">Informações de Usuário</h5>
                <table class="table table-sm">
                    <tbody>
                        <tr>
                            <th scope="row">Nome Completo</th>
                            <td>{{ user.full_name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Data de Nascimento</th>
                            <td>
                                {{ user.date_of_birth }}
                                <br>
                                ( {{ user.get_idade }} anos )
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">CPF</th>
                            <td colspan="2">{{ user }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Apto a realizar agendamento</th>
                            <td>
                                {% if user.is_able_to_schedule %}
                                    Sim
                                {% else %}
                                    Não
                                {% endif %}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer d-flex justify-content-center">
                {% if user.is_able_to_schedule %}
                    <a href="{% url 'pages:agendamento' %}" class="btn btn-primary ">Realizar Agendamento</a>
                {% endif %}
            </div>
        {% else %}
            <h2>Verificamos que você não está autenticado no nosso sistema</h2>
            <div class="container d-flex justify-content-center">
                <a href="{% url 'pages:login' %}" class = "btn btn-primary mx-1">Entrar</a>
                <a href="{% url 'pages:signup' %}" class= "btn btn-primary mx-1">Cadastrar-se</a>
            </div>
        {% endif %}
    {% endblock %}